import traceback

from string import Template

from memos.llms.base import BaseLLM
from memos.log import get_logger
from memos.memories.textual.tree_text_memory.retrieve.retrieval_mid_structs import ParsedTaskGoal
from memos.memories.textual.tree_text_memory.retrieve.retrieve_utils import (
    FastTokenizer,
    parse_json_result,
)
from memos.memories.textual.tree_text_memory.retrieve.utils import TASK_PARSE_PROMPT


logger = get_logger(__name__)

# Hints that indicate a query is referential / elliptical and needs
# context augmentation from prior conversation.
# Multi-char hints are safe for plain substring matching.
_MULTI_CHAR_REFERENTIAL_HINTS = (
    "其他",
    "别的",
    "这个",
    "那个",
    "继续",
    "上面",
    "刚说",
    "other",
    "another",
    "it",
    "this",
    "that",
    "more",
)
# Single-char hints are only matched at the *start* of the query to avoid
# false positives like "还款计划" (contains "还") or "也门旅游" (contains "也").
_SINGLE_CHAR_REFERENTIAL_HINTS = ("再", "也", "还", "他", "她", "它")


class TaskGoalParser:
    """
    Unified TaskGoalParser:
    - mode == 'fast': directly use origin task_description
    - mode == 'fine': use LLM to parse structured topic/keys/tags
    """

    def __init__(self, llm=BaseLLM):
        self.llm = llm
        self.tokenizer = FastTokenizer()
        self.retries = 1

    def parse(
        self,
        task_description: str,
        context: str = "",
        conversation: list[dict] | None = None,
        mode: str = "fast",
        **kwargs,
    ) -> ParsedTaskGoal:
        """
        Parse user input into structured semantic layers.
        Returns:
            ParsedTaskGoal: object containing topic/concept/fact levels and optional metadata
        - mode == 'fast': use jieba to split words only
        - mode == 'fine': use LLM to parse structured topic/keys/tags
        """

        if mode == "fast":
            return self._parse_fast(
                task_description, context=context, conversation=conversation, **kwargs
            )
        elif mode == "fine":
            if not self.llm:
                raise ValueError("LLM not provided for slow mode.")
            return self._parse_fine(task_description, context, conversation, **kwargs)
        else:
            raise ValueError(f"Unknown mode: {mode}")

    def _parse_fast(
        self,
        task_description: str,
        *,
        conversation: list[dict] | None = None,
        **kwargs,
    ) -> ParsedTaskGoal:
        """
        Fast mode: simple jieba word split.

        If recent conversation history is available, a lightweight
        context-augmented query is generated by prepending the most
        recent user message content.  This prevents referential
        queries (e.g. "再找找其他价格优惠的") from drifting to
        unrelated older memories.
        """
        context = kwargs.get("context", "")
        use_fast_graph = kwargs.get("use_fast_graph", False)

        # ─── Lightweight context expansion (no LLM call) ────────────────
        # When conversation history exists, augment the query with the
        # most recent user message so that embedding search has enough
        # context to disambiguate referential / elliptical queries.
        augmented_query = task_description
        if conversation:
            recent_user_msgs = [
                msg["content"]
                for msg in conversation
                if isinstance(msg, dict)
                and msg.get("role") == "user"
                and isinstance(msg.get("content"), str)
                and msg["content"].strip()
            ]
            if recent_user_msgs:
                # The current query might already be the last item in the conversation
                # history. If so, we want the *previous* user message as context.
                if (
                    recent_user_msgs[-1].strip() == task_description.strip()
                    and len(recent_user_msgs) > 1
                ):
                    last_user_msg = recent_user_msgs[-2].strip()
                elif recent_user_msgs[-1].strip() != task_description.strip():
                    last_user_msg = recent_user_msgs[-1].strip()
                else:
                    last_user_msg = ""

                # Only augment if the query is short or looks referential.
                is_referential = (
                    len(task_description) < 20
                    or any(h in task_description for h in _MULTI_CHAR_REFERENTIAL_HINTS)
                    or any(task_description.startswith(ch) for ch in _SINGLE_CHAR_REFERENTIAL_HINTS)
                )
                if is_referential and last_user_msg:
                    # Truncate to avoid over-long embedding inputs.
                    # Head truncation preserves the topic anchor at the beginning
                    # of the prior message.
                    max_ctx = 120
                    if len(last_user_msg) > max_ctx:
                        last_user_msg = last_user_msg[:max_ctx]
                    augmented_query = f"{last_user_msg} {task_description}"

        if use_fast_graph:
            desc_tokenized = self.tokenizer.tokenize_mixed(augmented_query)
            return ParsedTaskGoal(
                memories=[augmented_query],
                keys=desc_tokenized,
                tags=desc_tokenized,
                goal_type="default",
                rephrased_query=augmented_query,
                internet_search=False,
                context=context,
            )
        else:
            return ParsedTaskGoal(
                memories=[augmented_query],
                keys=[],
                tags=[],
                goal_type="default",
                rephrased_query=augmented_query,
                internet_search=False,
                context=context,
            )

    def _parse_fine(
        self, query: str, context: str = "", conversation: list[dict] | None = None, **kwargs
    ) -> ParsedTaskGoal:
        """
        Slow mode: LLM structured parse.
        """
        try:
            if conversation:
                conversation_prompt = "\n".join(
                    [f"{each['role']}: {each['content']}" for each in conversation]
                )
            else:
                conversation_prompt = ""
            prompt = Template(TASK_PARSE_PROMPT).substitute(
                task=query.strip(), context=context, conversation=conversation_prompt
            )
            logger.info(f"Parsing Goal... LLM input is {prompt}")
            response = self.llm.generate(messages=[{"role": "user", "content": prompt}])
            logger.info(f"Parsing Goal... LLM Response is {response}")
            return self._parse_response(response, context=context)
        except Exception:
            logger.warning(f"Fail to fine-parse query {query}: {traceback.format_exc()}")
            return self._parse_fast(query, context=context)

    def _parse_response(self, response: str, **kwargs) -> ParsedTaskGoal:
        """
        Parse LLM JSON output safely.
        """
        # Ensure at least one attempt
        attempts = max(1, getattr(self, "retries", 1))

        for attempt_times in range(attempts):
            try:
                context = kwargs.get("context", "")
                response_json = parse_json_result(response)
                if not response_json:
                    raise ValueError("Parsed JSON is empty")

                return ParsedTaskGoal(
                    memories=response_json.get("memories", []),
                    keys=response_json.get("keys", []),
                    tags=response_json.get("tags", []),
                    rephrased_query=response_json.get("rephrased_instruction", None),
                    internet_search=response_json.get("internet_search", False),
                    goal_type=response_json.get("goal_type", "default"),
                    context=context,
                )
            except Exception as e:
                if attempt_times == attempts - 1:
                    raise ValueError(
                        f"Failed to parse LLM output: {e}\nRaw response:\n{response} retried: {attempt_times + 1}/{attempts}"
                    ) from e
                continue
